version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=changeme
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME=https://example.com
    volumes:
      - ../Data/images:/var/www/wallabag/web/assets/images
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.wallabag.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.wallabag.entrypoints=web-secure"
      - "traefik.http.routers.wallabag.middlewares=default-headers@file"
      - "traefik.http.routers.wallabag.service=wallabag"
      - "traefik.http.routers.wallabag.tls=true"
      - "traefik.http.services.wallabag.loadbalancer.server.port=80" # Proxied Port
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ../Data/mysql:/var/lib/mysql
  redis:
    image: redis:alpine
